export type ToolName =
    // Posts
    | 'create_post'
    | 'list_posts'
    | 'get_post'
    | 'delete_post'
    | 'retry_post'
    | 'validate_post'
    | 'get_post_stats'
    // Accounts
    | 'list_accounts'
    | 'get_connect_url'
    | 'connect_bluesky'
    | 'disconnect_account'
    | 'check_accounts_health'
    // Profiles
    | 'get_profile'
    | 'update_profile'
    // Analytics
    | 'get_analytics'
    | 'get_facebook_page_insights'
    | 'get_usage_stats'
    // Queue
    | 'list_queue_slots'
    | 'set_queue_slots'
    | 'get_next_queue_slot'
    | 'preview_queue_slots'
    // Inbox
    | 'list_conversations'
    | 'get_messages'
    | 'send_message'
    // Comments
    | 'list_comments'
    | 'reply_to_comment'
    | 'delete_comment'
    | 'update_comment_status'
    // Reviews
    | 'list_reviews'
    | 'reply_to_review'
    // Twitter
    | 'retweet_post'
    | 'undo_retweet'
    | 'bookmark_tweet'
    | 'remove_bookmark'
    | 'follow_user'
    | 'unfollow_user'
    | 'edit_published_tweet'
    // Media
    | 'get_upload_url'
    // Broadcasts
    | 'list_broadcasts'
    | 'create_broadcast'
    | 'send_broadcast'
    // Email
    | 'create_inbox'
    | 'send_email'
    | 'list_inboxes'
    | 'get_inbox'
    | 'delete_inbox'
    | 'list_messages'
    | 'get_message'
    | 'get_email_stats'
    | 'search_emails'
    | 'semantic_search';

type ToolCredits = Record<ToolName, number>;

export const toolCredits: ToolCredits = {
    // Posts
    create_post: 3,
    list_posts: 1,
    get_post: 1,
    delete_post: 1,
    retry_post: 2,
    validate_post: 1,
    get_post_stats: 1,
    // Accounts
    list_accounts: 1,
    get_connect_url: 1,
    connect_bluesky: 1,
    disconnect_account: 1,
    check_accounts_health: 2,
    // Profiles
    get_profile: 1,
    update_profile: 1,
    // Analytics
    get_analytics: 3,
    get_facebook_page_insights: 3,
    get_usage_stats: 1,
    // Queue
    list_queue_slots: 1,
    set_queue_slots: 2,
    get_next_queue_slot: 1,
    preview_queue_slots: 1,
    // Inbox
    list_conversations: 2,
    get_messages: 2,
    send_message: 2,
    // Comments
    list_comments: 2,
    reply_to_comment: 2,
    delete_comment: 1,
    update_comment_status: 1,
    // Reviews
    list_reviews: 2,
    reply_to_review: 2,
    // Twitter
    retweet_post: 2,
    undo_retweet: 1,
    bookmark_tweet: 1,
    remove_bookmark: 1,
    follow_user: 2,
    unfollow_user: 1,
    edit_published_tweet: 3,
    // Media
    get_upload_url: 1,
    // Broadcasts
    list_broadcasts: 1,
    create_broadcast: 3,
    send_broadcast: 5,
    // Email — only billable actions cost credits; reads/views are free
    create_inbox: 1,
    send_email: 1,
    list_inboxes: 0,
    get_inbox: 0,
    delete_inbox: 0,
    list_messages: 0,
    get_message: 0,
    get_email_stats: 0,
    search_emails: 0,
    semantic_search: 0,
};

export function getToolCredits(toolName: string): number {
    // Use ?? not || so an explicit 0 (free read action) is honored.
    return toolCredits[toolName as ToolName] ?? 1;
}
